'use strict';

module.exports = {
  async up(queryInterface) {
    const now = new Date();
    const future = (days) => new Date(now.getTime() + days * 24 * 60 * 60 * 1000);

    await queryInterface.bulkInsert('events', [
      {
        title: 'Đêm Nhạc Trịnh Công Sơn — Người Tình Mùa Đông',
        slug: 'dem-nhac-trinh-cong-son-nguoi-tinh-mua-dong',
        description: '<p>Đêm nhạc tưởng nhớ nhạc sĩ Trịnh Công Sơn với sự tham gia của các ca sĩ hàng đầu. Những bản tình ca bất hủ sẽ được thể hiện trong không gian âm nhạc đặc biệt tại Nhà hát Lớn Hà Nội.</p><p>Chương trình bao gồm: Diễm Xưa, Tình Xa, Hạ Trắng, Ru Tình, Cát Bụi...</p>',
        short_description: 'Đêm nhạc tưởng nhớ Trịnh Công Sơn tại Nhà hát Lớn Hà Nội',
        banner_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=1200',
        thumbnail_url: 'https://images.unsplash.com/photo-1493225457124-a3eb161ffa5f?w=400',
        category: 'music',
        venue_id: 1,
        start_time: future(15),
        end_time: new Date(future(15).getTime() + 3 * 60 * 60 * 1000),
        sale_start_time: future(-2),
        sale_end_time: future(14),
        status: 'on_sale',
        max_tickets_per_user: 4,
        queue_enabled: false,
        queue_batch_size: 50,
        created_by: 1,
        created_at: now,
        updated_at: now,
      },
      {
        title: 'BLACKPINK World Tour — BORN PINK Việt Nam',
        slug: 'blackpink-world-tour-born-pink-viet-nam',
        description: '<p>BLACKPINK lần đầu tiên đến Việt Nam trong World Tour BORN PINK! Sự kiện âm nhạc lớn nhất năm tại SVĐ Mỹ Đình với hàng ngàn khán giả.</p>',
        short_description: 'BLACKPINK World Tour tại SVĐ Mỹ Đình — sự kiện âm nhạc lớn nhất năm',
        banner_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=1200',
        thumbnail_url: 'https://images.unsplash.com/photo-1516450360452-9312f5e86fc7?w=400',
        category: 'music',
        venue_id: 2,
        start_time: future(30),
        end_time: new Date(future(30).getTime() + 4 * 60 * 60 * 1000),
        sale_start_time: future(1),
        sale_end_time: future(29),
        status: 'published',
        max_tickets_per_user: 4,
        queue_enabled: true,
        queue_batch_size: 100,
        created_by: 1,
        created_at: now,
        updated_at: now,
      },
      {
        title: 'Hài Kịch: Tết Này Tôi Về',
        slug: 'hai-kich-tet-nay-toi-ve',
        description: '<p>Chương trình hài kịch đặc sắc chào đón năm mới với sự góp mặt của các danh hài nổi tiếng. Những tiết mục hài hước, ý nghĩa về tình cảm gia đình dịp Tết.</p>',
        short_description: 'Chương trình hài kịch đặc sắc chào đón năm mới',
        banner_url: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=1200',
        thumbnail_url: 'https://images.unsplash.com/photo-1478737270239-2f02b77fc618?w=400',
        category: 'comedy',
        venue_id: 3,
        start_time: future(7),
        end_time: new Date(future(7).getTime() + 2.5 * 60 * 60 * 1000),
        sale_start_time: future(-5),
        sale_end_time: future(6),
        status: 'on_sale',
        max_tickets_per_user: 6,
        queue_enabled: false,
        queue_batch_size: 50,
        created_by: 1,
        created_at: now,
        updated_at: now,
      },
      {
        title: 'Vũ Cát Tường — KHÁC Live Concert',
        slug: 'vu-cat-tuong-khac-live-concert',
        description: '<p>Vũ Cát Tường trở lại với concert solo KHÁC — một hành trình âm nhạc đầy cảm xúc và bứt phá. Không gian GEM Center sẽ được thắp sáng bởi những ca khúc đỉnh cao.</p>',
        short_description: 'Concert solo đặc sắc của Vũ Cát Tường tại GEM Center',
        banner_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=1200',
        thumbnail_url: 'https://images.unsplash.com/photo-1459749411175-04bf5292ceea?w=400',
        category: 'music',
        venue_id: 4,
        start_time: future(21),
        end_time: new Date(future(21).getTime() + 3 * 60 * 60 * 1000),
        sale_start_time: future(-1),
        sale_end_time: future(20),
        status: 'on_sale',
        max_tickets_per_user: 4,
        queue_enabled: false,
        queue_batch_size: 50,
        created_by: 1,
        created_at: now,
        updated_at: now,
      },
      {
        title: 'Festival Âm Nhạc Đà Lạt — Mountain Music',
        slug: 'festival-am-nhac-da-lat-mountain-music',
        description: '<p>Festival âm nhạc ngoài trời đầu tiên tại Đà Lạt — nơi giao thoa giữa âm nhạc và thiên nhiên. Các nghệ sĩ indie, folk và acoustic từ khắp Việt Nam hội tụ.</p>',
        short_description: 'Festival âm nhạc ngoài trời tại Đà Lạt — âm nhạc giữa thiên nhiên',
        banner_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=1200',
        thumbnail_url: 'https://images.unsplash.com/photo-1506157786151-b8491531f063?w=400',
        category: 'festival',
        venue_id: 5,
        start_time: future(45),
        end_time: new Date(future(47).getTime() + 6 * 60 * 60 * 1000),
        sale_start_time: future(5),
        sale_end_time: future(44),
        status: 'published',
        max_tickets_per_user: 8,
        queue_enabled: false,
        queue_batch_size: 50,
        created_by: 1,
        created_at: now,
        updated_at: now,
      },
    ]);
  },

  async down(queryInterface) {
    await queryInterface.bulkDelete('events', null, {});
  },
};
